#' Generate inverse distance–weighted landscape attributes
#'
#' `hydroweight_attributes()` computes landscape attributes weighted by
#' inverse‑distance rasters generated by `hydroweight()`. The workflow follows the attribute‑weighting approach of
#' **Peterson et al. (2011)** <https://doi.org/10.1111/j.1365-2427.2010.02507.x>.
#' IMPORTANTLY, this function produces ***one*** set of summary statistics for a ***single*** combination of:
#' * a layer of interest (`loi`; e.g., land‑use polygons or rasters),
#' * a region of interest (`roi`; e.g., a catchment boundary), and
#' * one or more distance‑weighted rasters (`distance_weights`) to produce a
#' summary table of weighted and/or unweighted statistics.
#'
#' All spatial inputs are internally aligned to the CRS and grid geometry of
#' `distance_weights`. Alignment and clipping are handled through
#' `process_input()`.
#'
#' @param attributes_dir Character or `NULL`.
#'   Directory in which a **temporary working subdirectory** will be created
#'   for raster alignment and intermediate files.
#'   If `NULL` (default), a subdirectory is created under the system temp
#'   directory.
#'
#'   This behaviour mirrors the temporary‑workspace handling in `hydroweight()`,
#'   and enables reproducible temp‑folder placement during batch or parallel
#'   processing.
#'
#' @param loi Character (filepath to `.shp`/`.tif`), `sf`, `SpatVector`,
#'   `PackedSpatVector`, `RasterLayer`, `SpatRaster`, or `PackedSpatRaster`.
#'   The layer of interest whose attributes will be summarized (e.g.,
#'   land‑cover raster or polygons).
#'
#' @param loi_columns Character vector of attribute column names within `loi` to
#'   summarize. If `NULL`, all columns (for vectors) or all layers (for rasters)
#'   are used.
#'
#' @param loi_numeric Logical. If `TRUE`, columns in `loi_columns` are treated as
#'   numeric and summarized using continuous statistics.
#'   If `FALSE`, columns represent categorical variables and proportional
#'   summaries are returned.
#'
#' @param loi_numeric_stats Character vector specifying the statistics to
#'   compute for numeric `loi`. Options include:
#'   `"distwtd_mean"`, `"distwtd_sd"`, `"mean"`, `"sd"`, `"median"`, `"min"`,
#'   `"max"`, `"sum"`, `"cell_count"`.
#'   Statistics without the `"distwtd_"` prefix are unweighted ("lumped")
#'   summaries.
#'
#' @param roi Character (filepath to `.shp`/`.tif`), `sf`, `SpatVector`, `PackedSpatVector`,
#'   `RasterLayer`, `SpatRaster`, or `PackedSpatRaster`.
#'   Region of interest within which attributes are summarized (e.g., a single
#'   watershed polygon). If `NULL`, the full extent of `distance_weights[[1]]` is
#'   used.
#'
#' @param roi_uid Character. A unique identifier for the region of interest.
#'   Included as a column in the output attribute table.
#'
#' @param roi_uid_col Character. Name of the column in which to store
#'   `roi_uid` in the final attribute table.
#'
#' @param distance_weights Character (filepath to `.tif` or `.zip`) or
#'   a list of `SpatRaster` objects.
#'   These are the distance‑weighted rasters output from `hydroweight()`.
#'
#' @param remove_region Character or spatial object. Optional polygon or raster
#'   region to be excluded from calculations (e.g., lakes masked out of a
#'   catchment).
#'
#' @param return_products Logical. If `TRUE`, the function returns a list
#'   containing:
#'   1) the attribute summary table, and
#'   2) a list of intermediate rasters (masked `loi` × `distance_weights`) used
#'      to calculate the statistics.
#'   If `FALSE`, only the summary table is returned.
#'
#' @param clean_tempfiles Logical. If `TRUE` (default), temporary files and the
#' working directory are deleted on exit. Set to `FALSE` to retain intermediate
#' rasters for debugging.

#'
#' @return
#' If `return_products = FALSE`, a tibble containing weighted and unweighted
#' attribute statistics.
#'
#' If `return_products = TRUE`, a list with:
#'
#' * **`attribute_table`** — the summary statistics table, and
#' * **`return_products`** — a list (length = number of distance‑weight rasters),
#'   each containing:
#'   - the `loi` raster masked to the `roi` and `remove_region`, and
#'   - the corresponding masked `distance_weights` raster.
#'
#' @seealso
#' * [hydroweight()] for generating distance‑weighted rasters
#' * [process_input()] for input standardization and alignment
#'
#' @export
hydroweight_attributes <- function(
    attributes_dir = NULL,
    loi,
    loi_columns = NULL,
    loi_numeric,
    loi_numeric_stats = c("distwtd_mean", "distwtd_sd", "mean", "sd",
                          "median", "min", "max", "sum", "cell_count", "NA_cell_count"),
    roi = NULL,
    roi_uid,
    roi_uid_col = "ID",
    distance_weights,
    remove_region = NULL,
    return_products = TRUE,
    clean_tempfiles = TRUE
) {

  ## SETUP ---------------------------------------------------------------------

  ## Allowed choices
  valid_stats   <- c("distwtd_mean", "distwtd_sd", "mean", "sd",
                     "median", "min", "max", "sum", "cell_count", "NA_cell_count")
  loi_numeric_stats <- match.arg(loi_numeric_stats, choices = valid_stats, several.ok = TRUE)

  ## Assign resampling type
  loi_resample <- ifelse(loi_numeric, "bilinear", "near")

  ## Create a stable, unique working subdir (mirrors hydroweight pattern)
  if (!is.null(attributes_dir)) {
    own_tempdir <- file.path(attributes_dir,
                             paste0(roi_uid, "_hwa_tmp_", basename(tempfile())))
  } else {
    own_tempdir <- file.path(tempdir(),
                             paste0(roi_uid, "_hwa_tmp_", basename(tempfile())))
  }
  dir.create(own_tempdir, recursive = TRUE, showWarnings = FALSE)

  ## Set terra tempdir for out-of-memory rasters
  old_terra_opts <- terra::terraOptions(print = FALSE)
  terra::terraOptions(tempdir = own_tempdir, verbose = FALSE)

  ## Ensure cleanup / terra options restoration happen even on error
  on.exit({
    # restore terra options
    opts <- old_terra_opts
    opts$metadata <- NULL
    opts$names    <- NULL
    if (identical(opts$filetype, "")) opts$filetype <- NULL
    do.call(terra::terraOptions, opts)

    if (isTRUE(clean_tempfiles)) {
      unlink(own_tempdir, recursive = TRUE, force = TRUE)
      suppressWarnings(terra::tmpFiles(current = TRUE,
                                       orphan  = TRUE,
                                       old     = TRUE,
                                       remove  = TRUE))
    }
  }, add = TRUE)

  ## READ DISTANCE WEIGHTS -----------------------------------------------------
  if (inherits(distance_weights, "list")) {

    if ((inherits(distance_weights[[1]], "character") &&
         grepl("\\.tif$", distance_weights[[1]])) ||
        inherits(distance_weights[[1]], "PackedSpatRaster")) {

      distance_weights <- lapply(distance_weights, terra::rast)

    } else if (inherits(distance_weights[[1]], "SpatRaster")) {

      # already fine
      distance_weights <- distance_weights
    }

  } else if (inherits(distance_weights, "character")) {

    if (grepl("\\.tif$", distance_weights)) {
      distance_weights <- list(terra::rast(distance_weights))

    } else if (grepl("\\.zip$", distance_weights)) {
      fls <- utils::unzip(distance_weights, list = TRUE)
      fls <- file.path("/vsizip", distance_weights, fls$Name)
      distance_weights <- lapply(fls, terra::rast)
      names(distance_weights) <- sapply(distance_weights, names)

    } else {
      stop("'distance_weights' must be .zip, tif, or list of rasters")
    }
  }

  ## Unpack if PackedSpatRaster
  distance_weights <- lapply(distance_weights, function(x)
    if (inherits(x, "PackedSpatRaster")) {
      terra::rast(x)
    } else {x}
  )
  names(distance_weights) <- sapply(distance_weights, names)

  dw_ref <- distance_weights[[1]]

  ## PROCESS INPUTS ------------------------------------------------------------
  if (is.null(roi)) {

    roi <- dw_ref
    roi[!is.na(roi)] <- 1
    names(roi) <- "roi"

  } else {

    roi <- process_input(
      input       = roi,
      input_name  = "roi",
      align_to    = dw_ref,
      clip_region = dw_ref,
      resample_type = "near",
      working_dir = own_tempdir
    )

    if (inherits(roi, "SpatRaster") && terra::nlyr(roi) > 1) roi <- roi[[1]]
    if (inherits(roi, "SpatVector") && terra::ncol(roi) > 1) roi <- roi[, names(roi)[1]]
    names(roi) <- "roi"
  }

  ## Remove region if provided -------------------------------------------------
  remove_region <- process_input(
    input       = remove_region,
    input_name  = "remove_region",
    align_to    = dw_ref,
    clip_region = dw_ref,
    resample_type = "near",
    working_dir = own_tempdir
  )

  if (!is.null(remove_region)) {

    roi <- process_input(
      input       = roi,
      input_name  = "roi",
      align_to    = dw_ref,
      clip_region = dw_ref,
      resample_type = "near",
      working_dir = own_tempdir
    )[[1]]

    roi <- roi[[1]]
    names(roi) <- "roi"

    remove_region <- remove_region[[1]]
    names(remove_region) <- "remove_region"

    roi <- terra::mask(roi, remove_region, inverse = TRUE)
  }

  ## Convert ROI to polygon
  roi_p <- process_input(
    input       = roi,
    input_name  = "roi",
    align_to    = terra::vect("POLYGON ((0 -5, 10 0, 10 -10, 0 -5))",
                              crs = terra::crs(dw_ref)),
    resample_type = "near",
    working_dir = own_tempdir
  )

  loi <- process_input(
    input                 = loi,
    input_name            = "loi",
    input_variable_names  = loi_columns,
    align_to              = dw_ref,
    clip_region           = roi,
    resample_type         = loi_resample,
    working_dir           = own_tempdir
  )

  ## Process distance weights with remove_region applied -----------------------
  distance_weights <- lapply(distance_weights, process_input,
                             align_to = dw_ref,
                             clip_region = roi,
                             resample_type = "bilinear",
                             working_dir = own_tempdir)

  ## CALCULATE LOI STATISTICS --------------------------------------------------

  ## Generate initial table
  loi_stats <- list(stats::setNames(roi_uid, roi_uid_col) |> unlist())
  names(loi_stats) <- roi_uid_col
  (loi_stats <- list(UID = loi_stats))

  if (loi_numeric) {

    ## Helper for global stats
    fun_global <- function(x, fun) terra::global(x, fun, na.rm = TRUE) |> unlist()

    if ("mean"   %in% loi_numeric_stats) { loi_mean   <- fun_global(loi, "mean") } else { loi_mean <- NULL }
    if ("sd"     %in% loi_numeric_stats) { loi_sd     <- fun_global(loi, "sd") }   else { loi_sd   <- NULL }
    if ("median" %in% loi_numeric_stats) { loi_median <- terra::global(loi, \(x) stats::median(x, na.rm = TRUE)) |> unlist() |> stats::setNames("median") } else { loi_median <- NULL }
    if ("min"    %in% loi_numeric_stats) { loi_min <- fun_global(loi, "min") } else { loi_min <- NULL }
    if ("max"    %in% loi_numeric_stats) { loi_max <- fun_global(loi, "max") } else { loi_max <- NULL }
    if ("sum"    %in% loi_numeric_stats) { loi_sum <- fun_global(loi, "sum") } else { loi_sum <- NULL }

    if ("cell_count" %in% loi_numeric_stats) {
      cc <- fun_global(!is.na(loi), "sum")
      loi_cell_count <- cc
      loi_cell_count <- stats::setNames(
        loi_cell_count,
        paste0(rep("cell_count", length(loi_cell_count)), seq_len(length(loi_cell_count)))
      )
    } else {
      loi_cell_count <- NULL
    }

    if ("NA_cell_count" %in% loi_numeric_stats) {
      roi_cc <- terra::global(roi, "sum", na.rm = TRUE)
      loi_NA_cell_count <- unlist(rep(roi_cc, length(loi_cell_count))) - unlist(loi_cell_count)
      loi_NA_cell_count <- stats::setNames(
        loi_NA_cell_count,
        paste0(rep("NA_cell_count", length(loi_NA_cell_count)),
               seq_len(length(loi_cell_count)))
      )
    } else {
      loi_NA_cell_count <- NULL
    }

    lumped <- list(
      mean = loi_mean,
      sd = loi_sd,
      median = loi_median,
      min = loi_min,
      max = loi_max,
      sum = loi_sum,
      cell_count = loi_cell_count,
      NA_cell_count = loi_NA_cell_count
    )

    ## ---- Naming fix with fallback ------------------------------------------
    # 1) Determine labels for each layer: prefer `loi_columns`; otherwise use
    #    raster layer names; otherwise generate "layer1..layerN".
    nlyr <- terra::nlyr(loi)
    fallback_names <- tryCatch(terra::names(loi), error = function(e) NULL)

    label_vec <- if (!is.null(loi_columns)) {
      if (length(loi_columns) != nlyr) {
        warning(sprintf(
          "Length of 'loi_columns' (%d) does not match number of layers (%d). Truncating/recycling.",
          length(loi_columns), nlyr
        ))
      }
      rep_len(loi_columns, nlyr)
    } else if (!is.null(fallback_names) && length(fallback_names) == nlyr) {
      fallback_names
    } else {
      paste0("layer", seq_len(nlyr))
    }

    # 2) Apply names to each metric vector safely.
    #    Handles cases with or without numeric suffixes in 'old' names.
    lumped <- lapply(lumped, function(x) {
      if (is.null(x)) return(NULL)

      old <- names(x)
      # If no names exist, fabricate indices 1..length(x)
      if (is.null(old)) {
        idx <- seq_along(x)
        metric_base <- ""
      } else {
        # Extract numeric index at the end (e.g., min1 -> 1), NA if no number
        idx <- suppressWarnings(as.integer(sub(".*?(\\d+)$", "\\1", old)))
        # Extract non-numeric prefix (e.g., "min", "mean", "cell_count")
        metric_base <- sub("^(.*?)(\\d+)$", "\\1", old)

        # If there is no numeric suffix (single-layer case), treat all as layer 1
        idx[is.na(idx)] <- 1
        # If base didn’t change (i.e., no digits), then base is whole name
        # but we still want the metric tag (e.g., "median" not "median1")
        # For safety, strip trailing digits only:
        metric_base <- sub("\\d+$", "", old)
      }

      # Ensure indices map into label_vec
      idx <- pmin(pmax(idx, 1L), length(label_vec))

      # Build "<layer_label>_<metric_base>" ensuring one underscore
      # Normalize metric base (trim, remove extra underscores)
      metric_base_clean <- gsub("_+", "_", trimws(metric_base))
      metric_base_clean <- sub("^_", "", metric_base_clean)  # no leading "_"
      metric_base_clean <- sub("_$", "", metric_base_clean)  # no trailing "_"

      new_names <- paste0(label_vec[idx], "_", metric_base_clean)
      names(x) <- new_names
      x
    })

    loi_stats <- c(loi_stats, list(lumped = lumped))

    distance_weights_attributes <- lapply(distance_weights[
      sapply(distance_weights, names) != "lumped"], function(dw) {

        loi_dist <- loi * dw
        names(loi_dist) <- names(loi)

        loi_sum <- terra::global(loi_dist, "sum", na.rm = TRUE)
        dw_sum  <- terra::global(dw, "sum", na.rm = TRUE)

        out_mean <- NULL
        out_sd   <- NULL

        if ("distwtd_mean" %in% loi_numeric_stats) {
          out_mean <- unlist(loi_sum) / unlist(dw_sum)
          names(out_mean) <- paste0(names(loi), "_", names(dw), "_distwtd_mean")
        }

        if ("distwtd_sd" %in% loi_numeric_stats) {
          mu <- out_mean
          term1 <- terra::global((dw * (loi - mu)^2), "sum", na.rm = TRUE)
          M     <- terra::global(dw != 0, "sum", na.rm = TRUE)
          term2 <- ((M - 1) / M) * dw_sum
          out_sd <- sqrt(unlist(term1) / unlist(term2))
          names(out_sd) <- paste0(names(loi), "_", names(dw), "_distwtd_sd")
        }

        tmp <- list(distwtd_mean = out_mean,
                    distwtd_sd   = out_sd)

        if (return_products)
          tmp <- c(tmp, list(loi_dist_rast = loi_dist))

        tmp
      })

    distance_weights_attributes

    if ("lumped" %in% sapply(distance_weights, names)) {
      distance_weights_attributes$lumped <- list(loi_dist_rast = loi)
    }

  } else {

    ## Categorical statistics --------------------------------------------------
   distance_weights_attributes <- lapply(distance_weights, function(dw) {

      loi_dist <- loi * dw
      names(loi_dist) <- names(loi)

      loi_sum <- terra::global(loi_dist, "sum", na.rm = TRUE)
      dw_sum  <- terra::global(dw,       "sum", na.rm = TRUE)

      pct <- unlist(loi_sum) / unlist(dw_sum)
      names(pct) <- paste0(names(loi), "_", names(dw), "_prop")

      tmp <- list(pct_distwtd = pct)
      if (return_products)
        tmp <- c(tmp, list(loi_dist_rast = loi_dist))
      tmp
    })
  }

  ## PREPARE OUTPUTS -----------------------------------------------------------
  final_out_table <- lapply(distance_weights_attributes, function(x)
    x[names(x) != "loi_dist_rast"]
  )
  final_out_table <- c(loi_stats, final_out_table)

  final_out_table

  final_out_table_nms <- lapply(names(final_out_table), function(x)
    lapply(names(final_out_table[[x]]), function(y)
      names(final_out_table[[x]][[y]])
    )
  )
  final_out_table_nms <- unlist(final_out_table_nms)

  final_out_table <- tibble::enframe(unlist(final_out_table)) |>
    tidyr::pivot_wider() |>
    dplyr::mutate(dplyr::across(
      c(dplyr::everything(), -dplyr::any_of(roi_uid_col)),
      as.numeric
    )) |>
    dplyr::mutate(dplyr::across(
      dplyr::ends_with("_prop"),
      ~ ifelse(is.na(.), 0, .)
    ))

  colnames(final_out_table) <- final_out_table_nms
  final_out_table <- dplyr::distinct(final_out_table)

  return_list <- list(attribute_table = final_out_table)

  if (return_products) {
    final_out_rasts <- lapply(distance_weights_attributes, function(x)
      x[names(x) == "loi_dist_rast"]
    )
    final_out_rasts <- lapply(final_out_rasts, function(x)
      lapply(x, terra::wrap)
    )
    return_list <- c(return_list, list(return_products = final_out_rasts))
  }

  return(return_list)
}

